name: Pull from Source Repo

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  workflow_dispatch:  # Allows manual trigger

jobs:
  pull:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout destination repo
        uses: actions/checkout@v2
        with:
          persist-credentials: false  # Prevents using the default token for pushing

      - name: Set up Git
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"

      - name: Pull changes from source repo
        run: |
          git remote add source https://github.com/nestjs/docs.nestjs.com.git
          git fetch source
          git checkout main  # Ensure you're on the correct branch
          git merge source/main --allow-unrelated-histories || echo "No changes to merge"

      - name: Check for changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "Changes detected, preparing to push."
            git push origin main --force
          else
            echo "No changes to push."
          fi
